export const config = {
  PIN_LENGTH: 8,
  MAX_GROUP_MEMBERS: 50,
  MAX_MESSAGE_LENGTH: 2000,
  MAX_STATUS_LENGTH: 140,
  MAX_DISPLAY_NAME_LENGTH: 30,
  MESSAGES_PER_PAGE: 30,
  TYPING_DEBOUNCE_MS: 300,
  TYPING_TIMEOUT_MS: 3000,
  MESSAGE_PREVIEW_LENGTH: 100,
  TASK_TITLE_MAX_LENGTH: 200,
} as const;
